name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for both server and client
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd server && npm install
          cd ../client && npm install

      - name: Build client
        run: |
          cd client && npm run build

      - name: Run server tests
        run: |
          cd server && npm test

      - name: Run client tests
        run: |
          cd client && npm test
